#!/bin/bash

BSP_TOP_DIR=$PWD
OUTPUT_DIR=$BSP_TOP_DIR/output
ROOTFS_DIR=$BSP_TOP_DIR/output/rootfs
YAFFSTOOL_DIR=$BSP_TOP_DIR/yaffstool
TOOLCHAIN_DIR=$BSP_TOP_DIR/toolchain
KERNEL_DIR=$BSP_TOP_DIR/linux
BUSYBOX_DIR=$BSP_TOP_DIR/busybox
DRVTEST_DIR=$BSP_TOP_DIR/drvtest
ZLIB_DIR=$BSP_TOP_DIR/zlib
LIBID3TAG_DIR=$BSP_TOP_DIR/libid3tag
LIBMAD_DIR=$BSP_TOP_DIR/libmad
MADPLAY_DIR=$BSP_TOP_DIR/madplay

export ARCH=arm
export CROSS_COMPILE=$TOOLCHAIN_DIR/bin/arm-mini2440-linux-gnueabi-

cd $KERNEL_DIR
sh build linux

cd $BUSYBOX_DIR
sh build busybox

cd $DRVTEST_DIR
make && make install

cd $ZLIB_DIR
sh build zlib

cd $LIBID3TAG_DIR
sh build libid3tag

cd $LIBMAD_DIR
sh build libmad

cd $MADPLAY_DIR
sh build madplay

cd $BSP_TOP_DIR
sh make-rootfs.sh

