#!/bin/bash
set -e

BSP_TOP_DIR=$PWD
OUTPUT_DIR=$BSP_TOP_DIR/output
ROOTFS_DIR=$BSP_TOP_DIR/output/rootfs
YAFFSTOOL_DIR=$BSP_TOP_DIR/yaffstool
TOOLCHAIN_DIR=$BSP_TOP_DIR/toolchain
KERNEL_DIR=$BSP_TOP_DIR/linux
BUSYBOX_DIR=$BSP_TOP_DIR/busybox
DRVTEST_DIR=$BSP_TOP_DIR/drvtest
ZLIB_DIR=$BSP_TOP_DIR/zlib
LIBID3TAG_DIR=$BSP_TOP_DIR/libid3tag
LIBMAD_DIR=$BSP_TOP_DIR/libmad
MADPLAY_DIR=$BSP_TOP_DIR/madplay

cd $KERNEL_DIR
sh build

cd $BUSYBOX_DIR
sh build

cd $DRVTEST_DIR
sh build

cd $ZLIB_DIR
sh build

cd $LIBID3TAG_DIR
sh build

cd $LIBMAD_DIR
sh build

cd $MADPLAY_DIR
sh build

cd $BSP_TOP_DIR
sh make-rootfs.sh

