#!/bin/bash

BSP_TOP_DIR=$PWD
OUTPUT_DIR=$BSP_TOP_DIR/output
ROOTFS_DIR=$BSP_TOP_DIR/output/rootfs
YAFFSTOOL_DIR=$BSP_TOP_DIR/yaffstool
TOOLCHAIN_DIR=$BSP_TOP_DIR/toolchain
KERNEL_DIR=$BSP_TOP_DIR/linux
BUSYBOX_DIR=$BSP_TOP_DIR/busybox
DRVTEST_DIR=$BSP_TOP_DIR/drvtest
ZLIB_DIR=$BSP_TOP_DIR/zlib
LIBID3TAG_DIR=$BSP_TOP_DIR/libid3tag
LIBMAD_DIR=$BSP_TOP_DIR/libmad
MADPLAY_DIR=$BSP_TOP_DIR/madplay
ALSALIB_DIR=$BSP_TOP_DIR/alsa-lib
ALSAUTILS_DIR=$BSP_TOP_DIR/alsa-utils

cd $KERNEL_DIR
sh build distclean

cd $BUSYBOX_DIR
sh build distclean

cd $DRVTEST_DIR
sh build distclean

cd $ZLIB_DIR
sh build distclean

cd $LIBID3TAG_DIR
sh build distclean

cd $LIBMAD_DIR
sh build distclean

cd $MADPLAY_DIR
sh build distclean

cd $ALSALIB_DIR
sh build distclean

cd $ALSAUTILS_DIR
sh build distclean

cd $BSP_TOP_DIR
rm -rf output


