#!/bin/bash
set -e

BSP_TOP_DIR=$PWD/..
OUTPUT_DIR=$BSP_TOP_DIR/output
ROOTFS_DIR=$BSP_TOP_DIR/output/rootfs
TOOLCHAIN_DIR=$BSP_TOP_DIR/toolchain

export ARCH=arm
export CROSS_COMPILE=$TOOLCHAIN_DIR/bin/arm-mini2440-linux-gnueabi-

build_menuconfig()
{
    if [ ! -e .config ]; then
        echo -e "\n\t\tUsing default config... !\n"
        cp mini2440_defconfig .config
    fi
    make menuconfig
}

build_busybox()
{
    if [ ! -e .config ]; then
        echo -e "\n\t\tUsing default config... !\n"
        cp mini2440_defconfig .config
    fi

    make -j2 && make install
}

case "$1" in
"")
    build_busybox
    ;;
menuconfig)
    build_menuconfig
    ;;
clean)
    make clean
    ;;
distclean)
    make distclean
    ;;
esac


