#!/bin/bash
set -e

BSP_TOP_DIR=$PWD/..
OUTPUT_DIR=$BSP_TOP_DIR/output
ROOTFS_DIR=$BSP_TOP_DIR/output/rootfs
TOOLCHAIN_DIR=$BSP_TOP_DIR/toolchain

export CC=$TOOLCHAIN_DIR/bin/arm-mini2440-linux-gnueabi-gcc

build_zlib()
{
    if [ ! -e configure.log ]; then
        ./configure --prefix=$ROOTFS_DIR/usr
    fi

    make && make install
}

case "$1" in
"")
    build_zlib
    ;;
clean)
    make clean
    ;;
distclean)
    make distclean
    ;;
esac

